CREATE TABLE IF NOT EXISTS wells (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS equipment (
    id INTEGER PRIMARY KEY AUTOINCREMENT ,
    name VARCHAR(32) NOT NULL ,
    well_id INTEGER ,
    FOREIGN KEY (well_id) REFERENCES wells (id)
);